name: validate
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  setup:
    # ignore all-contributors PRs
    if: ${{ !contains(github.head_ref, 'all-contributors') }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [14, 16]
    runs-on: ${{ matrix.os }}
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: ⎔ Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Unit test
        run: npm run test:unit:ci

      - name: Build
        run: npm run build

      - name: E2E test
        run: npm run e2e:headless:ci
