name: validate
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  setup:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [16]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: Install
        run: npm install

      - name: Unit test
        run: npm run test:unit:ci

      - name: Build
        run: npm run build

      - name: E2E test
        run: npm run test:e2e:ci
